language: node_js
node_js:
    - "lts/*"
sudo: false
install:
    - npm install
script:
    - npm run-script test
after_success:
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
branches:
    only:
        - develop
