name: Sync to Upstream

on:
  schedule:
    - cron:  '0 7 * * 1,4'
    # scheduled at 07:00 every Monday and Thursday
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync HEAD with upstream latest

    steps:
    # Step 1: run a standard checkout action, provided by github
    - name: Checkout HEAD
      uses: actions/checkout@v2
      with:
        ref: develop
    
    # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
    - name: Pull upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v2.3
      with:
        upstream_repository: conwetlab/ngsi-proxy
        upstream_branch: develop
        target_branch: develop                       # optional
        github_token: ${{ secrets.GITHUB_TOKEN }}   # optional, for accessing repos that require authentication
        git_pull_args: '--allow-unrelated-histories'
    - name: Revert if no changes
      run: |
        DIFF=$(git diff --shortstat  HEAD HEAD^1)
        if [ "$DIFF" == "" ]; then
          git reset --hard HEAD^1
          git push -f
        fi
